# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Calimpio.BitChat
PackageVersion: 1.0.0
InstallerType: portable
Commands:
  - BitChat
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/user-attachments/files/28670853/BitChat_v1.0.0.zip
    InstallerSha256: 74064afb70b37ffa45503b292a01c51ecd8568f560b96672476eb65974b2be5f
ManifestType: installer
ManifestVersion: 1.6.0
