# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Calimpio.BitChat
PackageVersion: 1.0.0
InstallerType: portable
Commands:
  - BitChat
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/user-attachments/files/28670853/BitChat_v1.0.0.zip
    InstallerSha256: e14ef6f9060493af727f480e4a98a3b44244588369281249142454539deec7a8
ManifestType: installer
ManifestVersion: 1.6.0
