# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Calimpio.BitChat
PackageVersion: 1.0.0
InstallerType: portable
Commands:
  - BitChat
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/user-attachments/files/28670853/BitChat_v1.0.0.zip
    InstallerSha256: 35d768355e946db535405f63766f4a46b8e45f5f2f1cdd633d05e9dd3783ea7a
ManifestType: installer
ManifestVersion: 1.6.0
